# Typus Roles Configuration File
#
# In this file you can configure the actions available for each of your 
# models on the application.
#
#     admin:
#       Post: create, read, update, delete
#       Category: create, read, update, delete
#
#     editor:
#       Post: create, read, update
#       Category: read, update
#
# You can also define `resources` which are not related to a model, 
# for example to control MemCached or see the Starling queue statistics.
#
#     admin:
#      Starling: index
#      MemCached: index, cleanup
#

admin:
  Day: create, read, update, delete
  Event: create, read, update, delete
  EventType: create, read, update, delete
  Place: create, read, update, delete
  PlaceType: create, read, update, delete
  Report: create, read, update, delete
  Strelki: create, read, update, delete
  User: create, read, update, delete
  AdminUser:  create, read, update, delete

user:
  Event: create, read
  Strelki: create, read
  Place: create, read