# Controller generated by Typus, use it to extend admin functionality.
class Admin::TaggingController < TypusController

  ##
  # This controller was generated because you have defined a resource 
  # on <tt>config/typus/XXXXXX_roles.yml</tt> which is a tableless model.
  #
  #     admin:
  #       Tagging: index
  #

  def index
  end

end
